ki-editor/ki-editor

src/app.rs, src/buffer.rs, src/components/editor.rs, src/components/test_editor.rs, src/grid.rs, src/layout.rs, src/main.rs, src/syntax_highlight/mod.rs, todo.md
I've demonstrated that highlighting only the visible content works pretty well.
And the performance improved tremendously.
However, there's a lot more things to be done.
TODO:
- Add test cases
- When the hidden parent lines wrapped, every syntax highlight spans becomes off
- Refactor the get_grid code
- Remove unused code
=> draft: proof of concept

keybindings.md, src/components/editor.rs, src/components/test_editor.rs, src/selection.rs, src/selection_mode/line_full.rs, src/selection_mode/line_trimmed.rs, src/selection_mode/mod.rs, src/test_app.rs, src/undo_tree.rs
Also introduced in this PR is a new movement called `ToParentLine`.
=> feat(up-down-hierarchy): line (trimmed) / line (full)

Cargo.lock, Cargo.toml, src/buffer.rs, src/git/hunk.rs
=> fix(autoformat): not working properly all the time

justfile, src/app.rs, src/components/editor.rs, src/components/prompt.rs, src/components/suggestive_editor.rs, src/layout.rs, src/lsp/code_action.rs, src/selection_mode/line_trimmed.rs, src/selection_mode/top_node.rs, src/test_app.rs
=> fix: navigating quickfix list destroys it sometimes

Cargo.lock, Cargo.toml, build.rs, src/app.rs, src/components/dropdown.rs, src/components/editor.rs, src/components/suggestive_editor.rs, src/grid.rs, src/lsp/code_action.rs, src/lsp/symbols.rs, src/quickfix_list.rs, src/themes/mod.rs, src/themes/vscode_light.rs
=> feat(prompt): fuzzy search ala fzf

src/components/editor.rs, src/components/test_editor.rs
=> feat(open): use max gap

src/lsp/process.rs
Root cause: cascades of errors
1. The LSP client sometimes sends incorrect request to LSP server.
2. LSP server pipes error to stderr.
3. LSP client does not read from stderr.
4. LSP client reads from stdout, got empty message.
5. LSP client decodes the empty message, and panicked.
Fixes: read from the LSP server's stderr if extracting from stdout failed.
Note: this is only tested on rust-analyzer.
=> fix(lsp/client): crash occasionally

docs/src/normal-mode/actions/index.md, docs/src/universal-keybindings.md, src/components/editor_keymap_legend.rs
To increase compatibility with Vim
=> keymap: use u for undo

src/components/editor.rs, src/components/prompt.rs
Latest entry should appear last, and vice versa.
=> feat(prompt): should reverse history

src/app.rs, src/components/suggestive_editor.rs
=> perf(suggestive_editor): only calls update_filer in Insert mode

src/components/prompt.rs, src/screen.rs
...if `leaves_current_line_empty` is false.
Closes #292.
=> fix(prompt): cursor not on last item

shared/src/languages.rs
=> feat(lsp): zig

docs/docs/normal-mode/actions/clipboard-related-actions.md, docs/docs/normal-mode/actions/index.mdx, docs/docs/normal-mode/movement-actions.md, docs/docs/normal-mode/selection-modes/local-global/text-search.md, docs/docs/recipes.md, src/components/editor_keymap_legend.rs, src/recipes.rs
Because this is a common operation.
=> keymap: change `! j` to `J` (Join)

src/lsp/process.rs
By limiting the number of failures in a fixed time frame.
=> fix(lsp): infinite loop when LSP failed to start

docs/docs/insert-mode/index.md, src/components/suggestive_editor.rs
=> tab keybind for use completion item

docs/docs/installation.md
Build with error when I didn't have `openssl-dev` install on PopOS.
=> Added install instruction for OpenSSL libs

docs/docs/normal-mode/core-movements.md, docs/docs/normal-mode/selection-modes/regex-based.md, src/components/editor.rs, src/components/editor_keymap_legend.rs, src/components/test_editor.rs, src/recipes.rs, src/selection.rs, src/selection_mode/character.rs, src/selection_mode/mod.rs, src/selection_mode/token.rs, src/selection_mode/word.rs
I believe this is more pragmatic than:
First/Last Token = First/Last token of current "sentence" First/Last Character = First/Last character of current line
=> feat(selection_mode/token,character): first/last use line/word boundary

shared/src/languages.rs
https://harelang.org/ for reference
=> add Hare support

shared/src/languages.rs, src/components/editor_keymap_config.rs
includes definition, tree-sitter, lsp and formatter
Elixir is a dynamic, functional language for building scalable and maintainable applications.
Elixir is one of the most desired languages in the Stack Overflow Developer Survey for multiple years running. Phoenix, *the* web framework for Elixir *is* the most desired web framework for multiple years running.
=> feat(languages/elixir): added elixir and heex

src/git/mod.rs
discover will start at provided path and look up the directory structure for a git repository.
Additionally, we then need to store the root folder of the .git repo, minus the .git/ directory in our path variable.
=> fix(git): use discover instead of open

src/cli.rs
add documentation to grammar and highlight-query commands as well as grammar sub-commands Build and Fetch
=> feat(cli): add --help docs to grammar and highlight-query commands

shared/Cargo.toml, shared/src/canonicalized_path.rs, src/app.rs
It will only be relative to home if the path is indeed relative to the users home directory.
=> feat(style): project path in status bar will be absolute or relative to home

shared/src/languages.rs
cpp file extension list was borrowed from helix
=> feat(languages): add common SQL and cpp file extensions

docs/docs/components/prompt.md, src/app.rs, src/components/dropdown.rs, src/components/prompt.rs, src/components/suggestive_editor.rs
`ctrl+o` will open all files in the Completion list that you have narrowed down with the file picker.
=> feat(explorer): Open multiple files with one action

src/buffer.rs, src/components/component.rs, src/components/editor.rs
Add separating lines in a few core files I am going to be working on. PR here for just those changes as to not inflate the PR with actual changes.
=> chore: add blank lines where appropriate in component, editor and buffer

src/themes/from_zed_theme.rs
Added popular themes. The most popular from Zed's extension list (at least). In addition, Modus, which is my favorite that I use everywhere :-)
=> feat(theme): added Dracula, Github, Modus, Nord and Tokyo Night

src/components/editor.rs, src/components/test_editor.rs, src/test_app.rs
Otherwise it will lead to weird behaviors.
=> fix(editor): surround-related actions should disable extension

shared/src/languages.rs
Hi there! I'm trying/learning Ki, loving it so far! There's so many cool ideas here!
I'm working with the languages Ruby and Roc quite a bit and added support for two languages I'm working with quite a bit: Roc and Ruby. Offering here to contribute them back in case it might be of benefit to others!
I tried to mirror the commit style I saw in other commits. Happy to make any changes, and of course no bad feelings if you don't feel like merging this!
=> Add support for language Ruby and Roc

docs/docs/configurations.md, src/components/editor_keymap.rs
Hello!
This PR adds support for the [workman](https://workmanlayout.org/) keyboard layout, as mentioned in https://github.com/ki-editor/ki-editor/issues/565.
I didn't wait to hear back on that issue before opening this, so I'm happy to make any changes if there's anything I missed. It seems to work okay locally!
=> feat(keyboard/layout): Workman

docs/docusaurus.config.ts, docs/package-lock.json, docs/package.json
=> feat(doc): search bar using Lunr.js

src/transformation.rs
As mentioned in https://github.com/ki-editor/ki-editor/discussions/574#discussion-8187498
=> fix(transformation/wrap): resulting lines contains extra whitespace

src/components/editor.rs, src/components/test_editor.rs, src/test_app.rs
Since Line is the default selection mode.
=> feat(editor): first line should be selected by default

docs/docs/normal-mode/selection-modes/primary.md
Refer https://github.com/ki-editor/ki-editor/issues/604#issuecomment-2853554226
=> doc(primary/syntax-node): update outdated keybindings

.gitignore, .vscode/launch.json, .vscode/tasks.json, biome.json, justfile, ki-jetbrains/src/kotlin/protocol/Types.kt, ki-protocol-types/src/lib.rs, ki-vscode/CHANGELOG.md, ki-vscode/README.md, ki-vscode/package-lock.json, ki-vscode/package.json, ki-vscode/src/managers/keyboard_manager.ts, ki-vscode/src/protocol/types.ts, package-lock.json, package.json, src/app.rs, src/components/editor_keymap.rs, src/components/editor_keymap_legend.rs, src/components/keymap_legend.rs, src/components/suggestive_editor.rs, src/embed/app.rs, src/integration_event.rs
Which includes:
1. Keymap Legend
2. Diagnostics
3. Generic Info
4. Git Hunk
=> feat(vscode): show info from Ki

src/lsp/goto_definition_response.rs
This implements missing handler and fixes issue mentioned in: https://github.com/ki-editor/ki-editor/pull/701#issuecomment-3116427601
=> feat(languages): support lsp link response in go to definition

docs/docs/installation.md
=> Update installation.md regarding typeshare

src/recipes.rs
In [Docs Intro](https://ki-editor.github.io/ki-editor/docs/introduction/), the last key be something like 'v' (to delete) instead of 'h' (entering insert mode).
=> fix(docs/intro) add assertion and change `delete` keystroke

docs/docs/normal-mode/actions/index.md, src/components/editor.rs, src/components/editor_keymap.rs, src/components/editor_keymap_legend.rs, src/components/test_editor.rs, src/recipes.rs
=> keymap(Open): replace Shift with SwapCursor
