ki-editor/ki-editor

event/src/event.rs
src/app.rs
src/components/editor.rs
src/components/editor_keymap_legend.rs
src/components/keymap_legend.rs
src/components/test_editor.rs
src/grid.rs
src/main.rs
src/selection_mode/bottom_node.rs
src/selection_mode/inside.rs
src/selection_mode/line_full.rs
src/selection_mode/line_trimmed.rs
src/selection_mode/mod.rs
src/selection_mode/syntax_tree.rs
src/selection_mode/top_node.rs
src/soft_wrap.rs
src/test_app.rs
src/transformation.rs
src/undo_tree.rs
todo.md

In this PR, the keymaps are rebound to be as close as Vim's keybinding to reduce learning friction.

Vimify keymaps

---

src/app.rs
src/components/dropdown.rs
src/components/suggestive_editor.rs
src/lsp/code_action.rs
src/test_app.rs

So that the user can search code action instead of navigating one by one.

feat(code_action): show as prompt

---

src/components/editor.rs
src/components/render_editor.rs
src/components/test_editor.rs

This is done by not passing hidden parent lines updates when rendering visible lines and vice versa.

fix(render): decorations of hidden parent lines polluting other parts

---

src/app.rs
src/components/component.rs
src/components/editor.rs
src/components/file_explorer.rs
src/components/keymap_legend.rs
src/components/prompt.rs
src/components/suggestive_editor.rs
src/components/test_editor.rs

This is fixed by intercepting `DispatchEditor`s that go from `App` to `Editor` at `SuggestiveEditor`.
However, this solution is not perfect, the `Paste` event from the terminal still does not update the suggestions.
But I shall fix it in the future.

fix(prompt): ctrl+u/ctrl+k not updating suggestions

---

docs/src/SUMMARY.md
docs/src/components/prompt.md
src/app.rs
src/components/file_explorer.rs
src/components/prompt.rs
src/context.rs
src/test_app.rs

This is to standardize the bookkeeping code,
instead of each kind of prompt storing their own history.
For example, the local search config histories.
After this refactor, every prompt has their own history.

refactor(prompt): add history key property

---

src/app.rs
src/components/editor.rs
src/components/editor_keymap_legend.rs
src/components/suggestive_editor.rs
src/layout.rs
src/lsp/manager.rs
src/lsp/process.rs
src/test_app.rs

This is because the LSP request params (i.e. cursor position) are prepared before the cursor position is updated.
This is mitigated by pushing the params preparation to be as late as possible

fix(lsp/signature help): incorrect cursor input

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
docs/src/SUMMARY.md
docs/src/normal-mode/actions/clipboard-related-actions.md
docs/src/normal-mode/actions/index.md
src/app.rs
src/clipboard.rs
src/components/editor.rs
src/components/editor_keymap_legend.rs
src/components/test_editor.rs
src/context.rs
src/main.rs
src/selection.rs
src/test_app.rs

To implement this feature, the mechanism that automatically decides to use either the system clipboard or the editor clipboard is removed, as it introduces complexities that obstruct extensibility.
Actions that use the clipboard are now parameterized with `use_system_clipboard`, which now means there are two versions of these actions, one that uses the editor clipboard and one that uses the system clipboard.

feat(editor): yank ring

---

src/components/editor.rs
src/components/test_editor.rs

This is fixed using the min gap instead of the max gap for Open Before.

fix(open line above): should not indent current line

---

src/buffer.rs
src/components/render_editor.rs
src/components/test_editor.rs
src/grid.rs
src/style.rs
src/themes/mod.rs

Rendering is one of the bottlenecks of Ki's performance, after analysis, syntax highlighting spans are found to be the root cause, due to its large amount (around 50k spans for a 2.7k lines Rust file).
Use binary search to quickly obtain all the syntax highlighting spans in view instead of iterating the whole list.
The following flamegraphs are generated by opening `editor.rs` of this repository, and continuously scrolling down (by holding `ctrl+d`) until it reaches like 1873.

perf(render_editor/get_grid): use binary search to filter syntax highlight spans

---

src/components/editor.rs
src/components/editor_keymap_legend.rs
src/components/test_editor.rs

perf(handle_key_event): compute node sexp lazily

---

src/components/editor.rs
src/components/editor_keymap_legend.rs
src/components/test_editor.rs
src/selection.rs
src/test_app.rs

Previously, deleting an extended selection only removed the highlighted content, contrary to the expected behavior of also deleting forward or backward based on the current selection mode. 
This PR fixes this issue, implementing the expected deletion behavior.

feat(editor): delete extended selection

---

docs/src/normal-mode/other-movements.md
docs/src/normal-mode/selection-modes/local-global/index.md
docs/src/universal-keybindings.md
src/app.rs
src/components/editor.rs
src/components/editor_keymap_legend.rs
src/components/test_editor.rs
src/context.rs
src/test_app.rs

Main change:
- Add `n`/`N` as "use last non-contiguous mode"
Other changes:
- Change `n`/`N` to `[`/`]`
- Change `[`/`]` to `ctrl+o`/`ctrl+i`
- Change `ctrl+o` to `ctrl+s` (might be temporary)
- Change `ctrl+q` to `ctrl+c`

feat(editor): use last non-contiguous selection mode

---

src/components/keymap_legend.rs

This is a quick fix to the panic in #332.
Still TODO; change the key binding, document it, perhaps investigate this issue in more detail.

fix panic on keybinding help, `@n`

---

docs/docs/normal-mode/selection-modes/local-global/index.md
src/components/editor_keymap_legend.rs
src/recipes.rs

Because `[`/`]` is so commonly used, they deserve more accessible keybindings.

keymap: change `[`/`]` to `N`/`n` & `n` to `;`

---

src/frontend/mod.rs
src/screen.rs

This is fixed by reversing the column-wise cell printing order, which was initially left-to-right.

fix(render): multi-width unicode character not showing most of the time

---

Cargo.lock
src/char_index_range.rs
src/components/test_editor.rs
src/selection_mode/mod.rs

This issue is caused by https://github.com/ki-editor/ki-editor/commit/ae1b19691f27de834ca526208eec43fa1d2ea654#diff-6ed05a70c735e96a3ca0ede9586069af860c4358f3fe59803b2e9a953fce9611R465

fix(selection_mode/line): not selecting current line if cursor on last whitespace of current line

---

docs/docs/normal-mode/actions/index.mdx
docs/docs/normal-mode/multi-cursor-mode.md
docs/docs/normal-mode/space-menu.md
docs/docs/pitch.md
src/app.rs
src/components/editor.rs
src/components/editor_keymap_legend.rs
src/components/prompt.rs
src/components/test_editor.rs
src/recipes.rs
src/selection.rs

Also consistentize multicursor keybindings:
| Action | Old | New |
|--|--|--|
|Add cursor to all matching selections|`space a`|`q q`|
|Keep primary cursor only|`space o`|`q o`|
|Remove matching selections | `alt+k` | `q r` |
|Maintain matching selections | `K` | `q m`|

feat(multicursor): add cursor till first/last selection

---

src/buffer.rs

Use `try_replace` instead of `replace_all` which calls `replacen` which panics on huge files. 
- https://docs.rs/fancy-regex/latest/fancy_regex/struct.Regex.html#method.replacen
- https://docs.rs/fancy-regex/latest/fancy_regex/struct.Regex.html#method.replace_all
- https://docs.rs/fancy-regex/latest/fancy_regex/struct.Regex.html#method.try_replacen

fix(global replace): panics if working directory contains very large text file

---

docs/docs/components/file-explorer.md
docs/docs/normal-mode/actions/index.md
docs/docs/normal-mode/core-movements.md
docs/docs/normal-mode/multi-cursor-mode.md
docs/docs/normal-mode/selection-modes/index.md
docs/docs/normal-mode/selection-modes/regex-based.md
docs/docs/normal-mode/selection-modes/syntax-node-based.md
src/components/editor.rs
src/components/editor_keymap_legend.rs
src/recipes.rs
src/selection_mode/line_trimmed.rs
src/selection_mode/mod.rs

This also entails no more generic Parent Line movements. This is because movements are supposed to be generic in meaning and then be specialized in different selection modes, not the other way around.

feat(selection_mode/line): left = parent line

---

src/components/editor.rs
src/recipes.rs

This is because after the file content changes, the selections are not clamped.

fix(docs/intro): sort TODO list demo not working

---

src/app.rs
src/cli.rs

It used to crash at `main.rs` where `cli::cli.unwrap()` was called because you'd just get an `Err` as the `edit` match arm wasn't able to handle a directory instead of a file. The file explorer does open but it is slow. I'm wondering if it's an issue of how I opened the file explorer or if it's an issue of the file explorer.
There is a bug where `ki edit ..` opens the current directory instead of the parent directory (will work on it) but I thought to just open the PR so it is kept track of it.

"ki edit ." now opens file explorer instead of crashing.

---

shared/src/languages.rs

"Gleam is a friendly language for building type-safe systems that scale!". It is growing in popularity, often times being compared to Rust. It compiles to the Beam VM (Erlang and Elixir) as well as directly to JavaScript.
https://gleam.run

feat(languages/gleam): added (definition, tree-sitter, lsp and formatter)

---

shared/src/languages.rs
src/components/editor_keymap_config.rs

This enables syntax highlighting when using ki as your git commit editor.
It also enables syntax highlighting for .gitignore, .gitattributes and .gitconfig files.

feat(languages/git): git commit, config, ignore and attributes

---

docs/docs/configurations.md
src/themes/mod.rs

This is a temporary measure until configuration is brought to Ki.
Ki will default to "VS Code (Light)". If KI_EDITOR_THEME is set, it will be used to find the correct theme. If it is set to an unknown theme, an error will appear along with a list of known themes.

feat(theme): configurable via KI_EDITOR_THEME environment variable

---

shared/src/languages.rs
src/app.rs
src/lsp/symbols.rs

Solves #473.
* Add support for parsing `Nested` in addition to `Flat` responses from LSP servers for `Document Symbol`.
* `DocumentSymbol` does not have file path information, therefore:
* Introduce new `go_to_current_component_range` function
* Introduce new `GoToCurrentComponentRange` `Dispatch` type. This type only has a range and will use the current component.

feat(lsp): support DocumentSymbol and children

---

src/components/editor_keymap_legend.rs

Add Write All, Write Quit All and Quit All commands to the space menu.
Command mode was not touched, it still remains unchanged. This could be the first step in getting away from it. Next step could be to simply unbind the ":" key and third step removing the code, if desired.
resolves #477

feat(keymap/space): add commands to space menu

---

docs/docs/normal-mode/other-movements.md
src/app.rs
src/components/editor_keymap_legend.rs

Will cycle through currently open file buffers. If you get to the end of the buffer list, it will start over at the beginning. Likewise, if you are at the start of the buffer list and go previous, it will cycle back to the last buffer.
When you close a buffer with `ctrl+c`, it will no longer be part of the buffer navigation.
Currently, this functionality is bound to `-` and `=`. Better keys may be `tab` and `shift+tab` but that has a conflict currently with Go back and Go forward.
This is different than previous/next opened files as that will cycle through files that you opened at some point in time. Closing a file does not remove it from the history stack.

feat(keymap): add previous/next buffer navigation

---

docs/docs/normal-mode/space-menu.md
src/app.rs
src/components/file_explorer.rs
src/components/prompt.rs
src/lsp/process.rs

Copy a single file from one location to another location.
* Added to explorer space context menu
* Added documentation
* Added notification to the LSP server that a new file was created

feat(explorer): add copy file to space menu for explorer

---

src/lsp/symbols.rs

This allows the symbols to order based on location in the source file not based on the string length, disregarding any positional meta data.

feat(lsp): symbol ranking

---

Cargo.lock
src/cli.rs

See #484.
This PR hides the "edit" command and makes it default.
Examples are given at the root of the ki-language git repo.
* `ki` -- opens [ROOT] window as it always has
* `ki readme.md` -- opens `readme.md`
* `ki src` -- opens the File Explorer for the `src` directory
* `ki log` -- opens a new file named `log`
* `ki @ log` -- prints log path and exits
* `ki @ grammar` -- shows grammar help and exits
* `ki @ grammar build` -- builds grammar and exits
New help output from `ki --help`:
```
Usage: ki [PATH] [COMMAND]
Commands:
@     Run commands
help  Print this message or the help of the given subcommand(s)
Arguments:
[PATH]
Options:
-h, --help     Print help
-V, --version  Print version
```
Output of `ki @ --help`
```
Run commands
Usage: ki @ <COMMAND>
Commands:
grammar          Build …
```

feat(cli): make edit the default command

---

shared/src/languages.rs

* Alphabetize the languages.rs list and order of definitions
* Alphabetize the attributes in each Language definition (providing standard for new definitions)
* Remove default values from Language definition, rely on ..Language::new() instead
* Removed unneeded complexity for javascript and typescript at the expense of a little duplicate code (not much)
By performing these actions the `languages.rs` file is easier to maintain and provides good examples for others to follow.

chore(languages): standardize order and attributes

---

docs/docs/normal-mode/space-menu.md
src/buffer.rs
src/components/editor.rs
src/components/editor_keymap_legend.rs
src/components/test_editor.rs
src/context.rs
src/list/grep.rs
src/test_app.rs

Currently when you press `enter` or exit the editor with `space q`, the file is saved always. This has a few undesired side effects:
1. If the file has LSP attached, it is notified the file has changed and work is done for no reason.
2. If the file has a formatter, it is called in an attempt to format the code. Again, work done for no reason.
3. If the file changes external to the editor, your external changes are blindly overwritten with the content in your buffer which you made no changes to.
If you have a long editing session, with many open files and a slow formatter, even quitting the editor can take a considerable time. If no changes are made, exiting is instant.
With this change, save is only attempted if the editor has been changed since it was read or last saved.

feat(editor): dirty detection for saving

---

docs/docs/normal-mode/other-movements.md
src/app.rs
src/components/editor.rs
src/components/editor_keymap_legend.rs
src/components/test_editor.rs
src/layout.rs

The numbers 1-5 can be used to "tag" an editor with that number. When pressing the number:
1. If no editors are tagged with the number pressed, the current editor will be tagged with that number.
2. If the current editor is already tagged with the number pressed, the tag will be cleared.
3. If another editor is tagged with the number pressed, you will jump to that editor.
This provides a very quick and efficient way of managing the most important files to you for your given editing session. The idea was built from other editor's plugins such as Harpoon, Reach and Lasso for Neovim.

feat: quick editor jumping

---

shared/src/language.rs
src/buffer.rs

The filename does not always tell the story as to what a file is. Shell scripts are a prime example. you may have a file named: `get_weather` and in it the first line contains `#!/bin/bash`. Currently, this file will not be detected as a bash script and will gain none of the LSP/Tree-sitter goodness that Ki has to offer.
With this change, if the filename and file extension does not yield a result on the language to use, the first line of the file content will be examined looking for a common shebang or mode header line. Mode header lines considered are the popular vim syntax and another syntax started by (I think) Emacs and used in other editors as well.
If the first line of a file contains any of the following, the Bash language will be assigned in Ki.
- `#!/bin/bash`
- `# vim: ft=bash` …

feat(language): if other methods fail, detect language from first line

---

flake.lock
flake.nix

Related with #514:
1. A build error occurs due to the Rust version not being specified in `flake.nix`.
2. A build error occurs due to missing dependencies on macOS.
1. Use the Rust version specified in `Cargo.toml` when build with Nix by rust-overlay.
2. Add the required dependencies for Darwin.

fix(flake): Build error by non-specifying Rust version

---

src/layout.rs
src/rectangle.rs

This is because the Tall layout is not suitable for displaying positional keymap.

feat(layout): only use Wide layout

---

docs/docs/normal-mode/other-movements.md
src/components/editor.rs
src/components/editor_keymap_legend.rs
src/components/test_editor.rs
src/recipes.rs
src/selection.rs
src/selection_mode/mod.rs

Also:
1. Renamed Swap Cursor with Anchor to Swap Cursor
2. Renamed Swap Selection End to Swap Anchor
These new naming are more consistent with their naming in the code.

feat(editor): should look backward when cursor swapped

---

shared/src/languages.rs

* Added grammar
* Added LSP command
Idris is a programming language designed to encourage Type-Driven Development. It is a pure, dependently typed, total functional programming language. In Idris, types are first-class constructs in the langauge. This means types can be passed as arguments to functions, and returned from functions just like any other value, such as numbers, strings, or lists.
https://www.idris-lang.org/

feat(languages/idris): Add support for Idris

---

Cargo.lock
Cargo.toml
src/cli.rs

So that I can use Ki as the page editor in Kitty term via:
```
map kitty_mod+e launch --stdin-source=@screen_scrollback --type=overlay ki
```
Of course, the ability to parse STDIN as an terminal editor app is expected by many other terminal apps such as gitui etc.

feat(cli): parse STDIN

---

src/components/editor.rs
src/components/editor_keymap.rs
src/components/suggestive_editor.rs
src/lsp/completion.rs

...of positional edit when there are more than one cursor.

feat(multicursor/completion): should use word replacement instead

---

src/app.rs
src/buffer.rs
src/components/component.rs
src/components/render_editor.rs
src/components/test_editor.rs
src/context.rs
src/frontend/mod.rs
src/grid.rs
src/layout.rs
src/rectangle.rs
src/screen.rs
src/syntax_highlight/mod.rs
src/themes/mod.rs

This is significant because the number of highlight spans for a medium-sized (~3k lines) Rust file can easily reach 50k.
And having to allocate and deallocate 50k Strings severely hurts performance.

perf(render_editor): change StyleKey::Syntax payload from String to usize

---

src/app.rs
src/buffer.rs
src/components/editor.rs
src/layout.rs
src/syntax_highlight/mod.rs

Implements a new batch ID system for syntax highlighting requests to track and validate the recency of updates. Only applies highlightings from the most recent batch, discarding outdated updates to eliminate visual flickering during rapid edits with concurrent syntax highlighting operations.
https://github.com/user-attachments/assets/10eeefb5-5a48-430f-ab01-f875b228f393
https://github.com/user-attachments/assets/7244208d-b9ca-4f0a-b66a-ce87e2cf6d42

feat(buffer/highlighting): introduce batch IDs to prevent UI flicker

---

docs/docs/installation.md

Personally I used
```sh
nix shell github:ki-editor/ki-editor nixpkgs#clang -c sh -c 'ki @ grammar fetch && ki @ grammar build'
```
to build the grammars ((the zig???) expects to see `c++`), after which 
```sh
nix shell github:ki-editor/ki-editor
```
is enough to have the editor available.

Fix grammar command

---

.github/workflows/rust.yml
src/buffer.rs
src/components/editor.rs
src/components/render_editor.rs
src/components/suggestive_editor.rs
src/components/test_editor.rs
src/generate_recipes.rs
src/recipes.rs
src/selection.rs
src/selection_mode/ast_grep.rs
src/selection_mode/character.rs
src/selection_mode/custom.rs
src/selection_mode/diagnostic.rs
src/selection_mode/git_hunk.rs
src/selection_mode/line_full.rs
src/selection_mode/line_trimmed.rs
src/selection_mode/local_quickfix.rs
src/selection_mode/mark.rs
src/selection_mode/mod.rs
src/selection_mode/naming_convention_agnostic.rs
src/selection_mode/regex.rs
src/selection_mode/syntax_node.rs
src/selection_mode/syntax_token.rs
src/selection_mode/token.rs
src/selection_mode/top_node.rs
src/selection_mode/word.rs
src/test_app.rs

Before this PR, executing `Select Word` when you have say 2000 cursors, the editor will hang, because the underlying code of Selection Mode relies mainly on an iterator method, which is to be implemented by the inheritors and also being used as the base for all movements such as left/right, up/down and first/last.
Turns out using an iterator method as the base is not super performant, the more performant way is to directly use methods under the `Rope` library, such as `Rope::char`, which is meant to be super performant.
Split the SelectionMode trait into two kinds:
1. Iterator-based (uses the existing SelectionMode's algorithm)
2. Position-based (new)
This PR only improves the performance of the following selection modes (which are also selection modes where the current selection around …

perf(selection_mode): replace `iter` with `get_current_selection_by_cursor`

---

docs/src/css/custom.css

Modify theme settings used default values was 1320px. At 1600px the keyboard map just fits.

feat(doc/keymap): css make default content area wider

---

docs/docs/components/file-explorer.md
docs/docs/normal-mode/core-movements.md
docs/docs/normal-mode/selection-modes/primary.md
src/components/dropdown.rs
src/components/editor.rs
src/components/editor_keymap.rs
src/components/editor_keymap_legend.rs
src/components/prompt.rs
src/components/test_editor.rs
src/components/test_editor_reveal.rs
src/recipes.rs
src/selection.rs
src/selection_mode/character.rs
src/selection_mode/line_full.rs
src/selection_mode/line_trimmed.rs
src/selection_mode/mod.rs
src/selection_mode/token.rs
src/selection_mode/word.rs
src/test_app.rs

The First/Last movement is renamed to Alpha/Beta to allow it to carry connotations beyond moving to the first or last selection.

feat(token): repurpose Alpha/Beta movement to mean symbols navigation

---

src/components/editor_keymap_printer.rs

So the width used for cell width was using length of all lines.
This is not very important, if you think its not worth bothering with that's fine. 😄 
I had noticed there was a lot of padding when Help or Space menu was showing the shift and option keys.
My terminal width on my right monitor was wide enough for data without the extra padding and it was bugging me that it was wrapping. Took a while and some more practice reading Rust but I got there.
The original code used the length of all 3 lines of text concatenated for width not the longest line in a multiline scenario.
In addition for general String processing the original code used `len()` and not `chars().count()` so it doesnt handle multi byte UTF-8. But I left it with `len()` for now as original was len().

fix(help/keymap): handle multiline description widths

---

Cargo.toml

So that the compiled binary size will be much smaller.

chore(Cargo.toml): disable debug by default

---

src/app.rs
src/components/render_editor.rs
src/grid.rs
src/test_app.rs
src/themes/mod.rs

| Before | After |
|--------|--------|
| <img width="1222" alt="image" src="https://github.com/user-attachments/assets/e986bb4f-d90e-4859-af8b-8cb7c30fa004" /> | <img width="1222" alt="image" src="https://github.com/user-attachments/assets/36ad781a-89fc-4942-a964-c6ba8e1fe8c4" /> |

feat(render): highlight cursor line number

---

.vscode/launch.json
.vscode/tasks.json
ki-vscode/README.md

This PR eliminates the need of opening another VS Code instance in the ki-vscode in order to debug the extension.

feat(dev/ki-vscode): simplify workflow

---

src/app.rs
src/components/editor_keymap_printer.rs
src/components/keymap_legend.rs

So that we can hide it when Ki is being used as a VS Code extension, since we have not mapped alt keys to VS Code yet.

feat(editor_keymap_printer): allow hiding Alt row

---

docs/docs/normal-mode/other-movements.md
src/components/editor_keymap.rs
src/components/editor_keymap_legend.rs
src/components/test_editor.rs

So that it will be usable in VS Code Ki, as these actions were previously bound to alt keys which are not handled by VS Code.

keymap: map previous/next historical selection to Backspace/Tab

---

docs/docs/normal-mode/selection-modes/primary.md
docs/docs/normal-mode/selection-modes/secondary/index.md
justfile
src/app.rs
src/components/editor_keymap.rs
src/components/editor_keymap_legend.rs
src/components/test_editor.rs
src/context.rs
src/recipes.rs

Keymap changes:
1. `n`/`N` is now bound to `Repeat last search (forward)`/`Repeat last search (backward)`
2. Global is changed from `n` to `\`
Reason:
Previously, Repeat Last Search is bound to `[ r` or `] r`, which is frankly a little tedious considering how often we need to repeat the last search.

keymap: promote Repeat Last Search to first layer

---

shared/src/languages.rs

XAML files are used by WPF, and AXAML files are used by Avalonia. They're XML files sytactically so XML tree sitter works fine

add support for xaml & axaml files

---

docs/docs/insert-mode/index.md
ki-vscode/package-lock.json
src/components/editor.rs
src/components/keymap_legend.rs
src/components/test_editor.rs
src/recipes.rs

This reverts a5fedfa.
Because I find the following flow annoying:
1. Enter Line selection mode
2. Execute Insert After
3. Type in a new word, say `foo`
4. Press esc to enter normal mode
5. I expect the cursor to be at somewhere near `foo`, but the cursor goes to the first non-whitespace character of the current line, because the last selection mode was Line, so the current line becomes selected, and so to go back to `foo`, I have to press a significant amount of keys.

revert(editor): enter normal mode select selection before cursor

---

src/components/editor.rs
src/components/test_editor.rs

https://github.com/ki-editor/ki-editor/blob/8826f9c2e911fecea054aa47fd6e6476776ae5b3/src/components/editor.rs#L1450-L1452
The code that handles jump mode also issued an `EnterNormalMode` dispatch, which will deactivate extension mode.
Change the mode to Normal mode without using `EnterNormalMode` (which actually does more than just changing the mode.

fix(editor): jump should not exit extend mode

---

src/app.rs
src/components/editor.rs
src/components/prompt.rs
src/components/suggestive_editor.rs
src/components/test_editor.rs
src/git/mod.rs
src/layout.rs
src/test_app.rs
src/ui_tree.rs

...after activating local git hunk.
This is solved by using the same ComponentKind for both Quickfix List Info and Selection Mode Info.
This issue occurred because previously, the local Git hunk info was coming from Selection Mode Info, which uses a different component kind than the info coming from Quickfix List Info.

fix(render): multiple info window rendered when activating global git hunk

---

justfile
src/themes/from_zed_theme.rs

**Preface**: The theme picker was listing some [legacy themes from zed](https://github.com/zed-industries/zed/discussions/24661). I have tried finding alternatives ports for some of them.
**Removed** (Could not find ports):
- Andromeda (could not find valid [port](https://github.com/ChocolateNao/andromeda-zed))
- Atelier
- Sandcastle
- Summercamp
**Changed** (Found valid ports):
- Rose Pine
- Solarized
**Added**:
- Gruber Darker
- Mqual Blue

fix(themes): remove/change legacy themes

---

docs/docs/universal-keybindings.md
src/buffer.rs
src/components/editor.rs
src/components/render_editor.rs
src/components/test_editor.rs
src/generate_recipes.rs
src/grid.rs
src/recipes.rs
src/test_app.rs

Align view currently does not work well, especially when we are using the Syntax Node selection mode.
This is because syntactic selection usually spans multiple lines, and we expect align center to center the whole selection, but now it just center the cursor.
Align top    = use selection first line
Align center = use selection middle
Align bottom = use selection last line
- https://github.com/ki-editor/ki-editor/issues/561

feat(editor/align): align consider multiple line selections

---

src/components/editor_keymap.rs
src/components/test_editor.rs
src/recipes.rs

1. Executing Find Mark (`n y`) is hard to press.
2. Mark (currently `y`) used to be on the left side of the keyboard.
3. This makes the Find (Local or Global) menu more consistent, as every item will solely be on the left side of the keyboard.

keymap: remap Mark to left side of keyboard

---

src/components/editor.rs
src/components/test_editor.rs

The `AlignViewTop` command fails to work correctly when the selection height is larger than the viewport height. Instead of aligning the selection to the top of the viewport as expected, the editor automatically centers the cursor.
During each render cycle, this function call chain executes:
```
App::get_screen
├── Layout::recalculate_layout
├── Component::set_rectangle
├── Editor::set_rectangle
└── Editor::recalculate_scroll_offset
```
The issue occurs in `Editor::recalculate_scroll_offset`, which unconditionally attempts to center the cursor whenever the selection height exceeds the viewport height. This centering behavior overrides the intended `AlignViewTop` positioning.
Add a guard condition in `Editor::set_rectangle` to skip calling `Editor::recalculate_scroll_offset` when the …

fix(editor): `AlignViewTop` not working if selection height exceeds viewport height

---

src/components/editor_keymap_printer.rs
src/components/keymap_legend.rs
src/test_app.rs

feat(keymap_legend): display stacked when width is too small but still large enough
